#!/usr/bin/env python3
import argparse
from grammaticommit import install

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('--global',
                        dest='globally',
                        action='store_true')
    args = parser.parse_args()

    install(args.globally or False)
